name: Release Swift library

on:
  push:
    tags:
      - "v*"

env:
  GITHUB_REF: "${{ github.ref }}"

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Cocoapods
      run: gem install cocoapods

    # shortcut version
    - uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.9
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
