name: Test Swift library

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.4.2"

    - name: Get swift version
      run: swift --version

    - name: Install Cocoapods
      run: gem install cocoapods

    - name: Install deps
      working-directory: ./Examples/CocoaPods
      run: pod install

    - name: Run tests
      working-directory: ./Examples/CocoaPods
      run: xcodebuild -workspace ZKSyncExample.xcworkspace -scheme ZKSyncExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' test
